### ISSUE TITLE
Pre-commit hook fails consistently

### ISSUE THREAD

**Issue by gokul-uf** [iranzo/blog-o-matic#8]
Hi,
I forked your repo and followed all the instructions. However, when I add some dummy content and push to main, the `pre-commit` GH Action always fails and without any log messages. See [here](https://github.com/gokul-uf/gokul-uf.github.io/actions?query=workflow%3Apre-commit) for the failed jobs.

Also, as potentially a consequence of this, I get a `404` error whenever I click on any articles in my blog. [Here](https://gokul-uf.github.io/) is my landing page if you would like to try it for yourself.

Could you please help me with the above two issues?

Thanks!

**Comment by gokul-uf** [comment]
Quick Update: The `404` was due to a name clash with another repo, but the `pre-commit` failure still exists

**Comment by iranzo** [comment]
Thanks @gokul-uf I'll be checking it

**Comment by iranzo** [comment]
It should be fixed in https://github.com/iranzo/blog-o-matic/commit/6dcb5d6e169f74005c74230f0119c5df4a08c7e5 and later.

Thanks for reporting!
Pablo
